146 - Improve categories grid
fjelltopp/ckanext-fjelltopp-theme pull request #45
Opened 2024-12-03 14:05 UTC by A-Souhei

## Title (delete after following this rule)

Your PR title should be prefixed with the Jira ticket ID, e.g. "ADX-123 very important feature".

## Description

Please include a summary of the change(s).
You should also include screenshots or videos of UI changes.

You should include a link to the JIRA ticket and also a sentence summary of the motivation.

Don't forget to reference all other pull requests which are associated to this one below, especially if merging need to be coordinated.
E.g.

relates fjelltopp/repository_name#issue_number

## Dependency Changes (delete if not applicable)

List any dependencies that have been removed/added/changed in this pull request and explain why.
Has the pipfile.lock or yarn.lock been updated?
If dependency management for this project is centralised, e.g. `adx_deploy` for ADR, please link to the coordinated PR in the project repo.

## Testing (delete if not applicable)

Please describe the rationale behind any new tests that have been added for this change, e.g.

- I have included automated unit tests for all features except V, because W
- I have included automated integration tests for X that do Y
- I have not included automated UI tests because Z
- I have manually carried out the following tests that I have been unable to automate: A, B, C

## Documentation (delete if not applicable)

Please describe any new technical documentation that has been added to Confluence for this change.

## Environment Changes (delete if not applicable)

Have any environment variable changes been committed as part of this pull request?
Is there a matching PR in fjelltopp/fjelltop-infrastructure for these changes?
Have any README or Confluence install instructions been updated to reflect this change?

## Internationalisation and Localisation (delete if not applicable)

Do any UI changes require internationalisation (i18n) or localisation (l10n) changes.
If new translations are required, have you created new Jira tickets for each language and informed the appropriate project manager?

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [ ] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.
- [ ] I have assigned at least one label to this PR: "patch", "minor", "major".

2024-12-09 09:48 UTC, ChasNelson1990 reviewed
> Should we make a special branch/tag for this one ?

@A-Souhei - what's your motivation for this?

2024-12-09 09:53 UTC, A-Souhei commented
@ChasNelson1990 This follows the same principles as what we did in WAC. Updating "group" and "organization" required a lot of templates modifications so using the po file was a lot less code changes.

2024-12-09 13:52 UTC, ChasNelson1990 commented
> My question is because may be not every CKAN applications needs this.

Can we no just have some sort of on / off flag in the extension config?

2024-12-10 07:22 UTC, A-Souhei commented
@ChasNelson1990 a code in bootstrap.sh is needed for it, if one does not add this code, will that be enough as a way to toggle it on / off?

2024-12-10 09:58 UTC, ChasNelson1990 commented
> @ChasNelson1990 a code in bootstrap.sh is needed for it, if one does not add this code, will that be enough as a way to toggle it on / off?

Maybe we should have an explicit variable rather than an implicit copy / paste?

2025-01-16 13:57 UTC, mixmixmix commented
@A-Souhei @ChasNelson1990 please agree how to proceed, it would be good to merge this PR.

2025-01-16 14:38 UTC, ChasNelson1990 requested changes
Let's get this PR moving again @A-Souhei.

I think to unblock my review and approval we need to do 2 things:

1. Please split this PR - the translation piece of work should be a unique PR compared to the CSS and styling work. As features they are really independent and for ease of review and also good code history I'd like them split into 2 PRs.
2. There seem to be large chunks of HTML that are copy and pasted from CKAN upstream just to add a class or id to an element - e.g. group_form.html is 41 lines of copy and paste essentially to add `class="dataset-form"`. This is going to make it very hard keeping ckanext-fjelltopp-theme in sync with CKAN versions in the future. Is there any way that we can either reuse existing CSS selectors or do this without all that copy paste?

2025-01-20 07:22 UTC, closed without merging